name: Sync Private to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório privado
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCOUNT_TOKEN }}

      - name: Configurar Git (como a conta pública)
        run: |
          git config --global user.name "Fasteninglove"  # Nome da conta pública
          git config --global user.email "fasteninglove@users.noreply.github.com"  # E-mail público do GitHub

      - name: Clonar repositório privado
        run: |
          git clone --bare https://${{ secrets.ACCOUNT_TOKEN }}@github.com/ViniciusSilveiraCampos/github-actions-test.git repo
          cd repo

      - name: Push para repositório público (autenticado como a conta pública)
        run: |
          git push --mirror https://${{ secrets.DEST_REPO_PAT }}@github.com/Fasteninglove/teste-repo.git

    env:
      ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
      DEST_REPO_PAT: ${{ secrets.DEST_REPO_PAT }}
